#
#
#  Makefile to create libArduinoCore.a for a specific board.
#
#
#
# Spec file of board to build for:

CXXSRC= Firmata.cpp utility/BLEStream.cpp utility/EthernetClientStream.cpp utility/SerialFirmata.cpp utility/WiFiStream.cpp
SRC=
HEADERS= Firmata.h Boards.h

LIB=../libarduinoutils.a

include ../Maketemplate
