#
#
#  Makefile to create libArduinoCore.a for a specific board.
#
#
#
# Spec file of board to build for:

CXXSRC=Wire.cpp
SRC=utility/twi.c

HEADERS=Wire.h utility/twi.h
LIB=../libarduinoutil.a

INC += -Iutility

include ../Maketemplate
