#
#
#  Makefile to create libArduinoCore.a for a specific board.
#
#
#
# Spec file of board to build for:

CXXSRC=CDC.cpp  HardwareSerial.cpp HardwareSerial0.cpp HardwareSerial1.cpp HardwareSerial2.cpp HardwareSerial3.cpp IPAddress.cpp PluggableUSB.cpp Print.cpp Stream.cpp Tone.cpp USBCore.cpp WMath.cpp WString.cpp abi.cpp new.cpp
SRC=WInterrupts.c hooks.c wiring.c wiring_analog.c wiring_digital.c wiring_pulse.c wiring_shift.c

HEADERS=Arduino.h Client.h HardwareSerial.h IPAddress.h PluggableUSB.h Print.h Printable.h Server.h Stream.h USBAPI.h USBCore.h USBDesc.h Udp.h WCharacter.h WString.h binary.h new.h

LIB=../libarduino.a

include ../Maketemplate
