#
#
#  Makefile to create libArduinoCore.a for a specific board.
#
#
#
# Spec file of board to build for:

CXXSRC=SoftwareSerial.cpp
SRC=

HEADERS=SoftwareSerial.h

LIB=../libarduinoutil.a

include ../Maketemplate
