#
#
#  Makefile to create libArduinoCore.a for a specific board.
#
#
#
# Spec file of board to build for:

CXXSRC = Sensirion.cpp
SRC=

HEADERS = Sensirion.h
LIB=../libarduinoutil.a

include ../Maketemplate
