#
#
#  Makefile to create libArduinoCore.a for a specific board.
#
#
#
# Spec file of board to build for:

CXXSRC=src/LiquidCrystal.cpp
SRC=

HEADERS=src/LiquidCrystal.h

LIB=../libarduinoutil.a

include ../Maketemplate
